tour/apps/tourism/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'tourism'

urlpatterns = [
    path('', main, name='main'),
    path('order-room/', OrderRoomView.as_view(), name='room_order'),
    path('status-change/', StatusChangeView.as_view(), name='status_change'),
    path('policy-change/', PolicyChangeView.as_view(), name='policy_change'),
    path('price-change/', PriceChangeView.as_view(), name='price_change'),
    path('status-retrieve-tour/<int:pk>',
         StatusRetrieveTourView.as_view(), name='status_retrieve'),
    path('status-retrieve-room/<int:pk>',
         StatusRetrieveRoomView.as_view(), name='status_retrieve'),
    path('status-retrieve-transfer/<int:pk>',
         StatusRetrieveTransferView.as_view(), name='status_retrieve'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('info-retrieve-tour/', InfoRetrieveToursView.as_view(),
         name='info_retrieve_tour'),
    path('info-retrieve-room/', InfoRetrieveRoomView.as_view(),
         name='info_retrieve_room'),
    path('info-retrieve-transfer/', InfoRetrieveTransferView.as_view(),
         name='info_retrieve_transfer'),
    path('remove-staff/', RemoveStaffView.as_view(), name='remove_staff'),
    path('order-transfer/', OrderTransferView.as_view(), name='order_transfer'),
    path('order-tour/', OrderTourView.as_view(), name='order_tour'),
    path('order-room/', OrderRoomView.as_view(), name='order_room'),
    path('order-transfer-client/', OrderClientTransferView.as_view(), name='order_transfer_client'),
    path('order-tour-client/', OrderClientTourView.as_view(), name='order_tour_client'),
    path('order-room-client/', OrderClientRoomView.as_view(), name='order_room_client'),
    path('retrieve-users/', RetrieveUsersView.as_view(), name='retrieve_users'),
    path('retrieve-orders/', RetrievesOrdersView.as_view(), name='retrieve_orders'),
    path('retrieve-users-orders/', RetrieveUsersOrdersView.as_view(),
         name='retrieve_users_orders'),
    path('register/', register, name='register'),
    #     path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

tour/tour/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from tour import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.tourism.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tour/templates/tour/change_password.html
{% extends 'base.html' %} {% block style %}
<link
  href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
  rel="stylesheet"
/>
{% endblock %} {% block title %}Statistics{% endblock title %} 
{% block content %}
<div class="intro">
  <h1>Смена пароля</h1>
  <div class="container">
    <form method="post">
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock content %}

tour/templates/tour/info_retrieve.html
{% extends 'base.html' %}

{% block style %}
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
{% endblock %}
{% block title %}{{ model_name }}{% endblock title %}
{% block content %}
<div class="intro">
    {% if form %}
    <h1>Выбор {{ model_name }}</h1>
    <form action="" method="post">
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
</div>

<div class="container">
    {% if info %}
    {% if model_name == 'Туры' %}
    <div class="info">
        <h2>Информация о туре</h2>
        <p>Название: {{ info.title }}</p>
        <p>Описание: {{ info.description }}</p>
        <p>Цена: {{ info.price }}</p>
        <p>Город: {{ info.city }}</p>
        <p>Рейтинг: {{ info.rating }}</p>
    </div>
    {% elif model_name == 'Трансферы' %}
    <div class="info">
        <h2>Информация о трансфере</h2>
        <p>Название: {{ info.title }}</p>
        <p>Описание: {{ info.description }}</p>
        <p>Места: {{ info.places }}</p>
        <p>Цена: {{ info.price }}</p>
        <p>Город: {{ info.city }}</p>
        <p>Рейтинг: {{ info.rating }}</p>
    </div>
    {% elif model_name == 'Номера' %}
    <div class="info">
        <h2>Информация о номере</h2>
        <p>Название: {{ info.title }}</p>
        <p>Описание: {{ info.description }}</p>
        <p>Кол-во мест: {{ info.places }}</p>
        <p>Цена: {{ info.price }}</p>
        <p>Город: {{ info.city }}</p>
        <p>Рейтинг: {{ info.rating }}</p>
        <p>Кол-во комнат: {{ info.quantity }}</p>
        <h2>Информация об отеле</h2>
        <p>Название: {{ info.hotel.title }}</p>
        <p>Описание: {{ info.hotel.description }}</p>
        <p>Город: {{ info.hotel.address.city }}</p>
        <p>Рейтинг: {{ info.hotel.rating }}</p>
    </div>
    {% endif %}
    {% endif %}
</div>
{% endblock content  %}

tour/templates/tour/login.html
{% extends "base.html" %} {% load static %} {% block content %}

<!-- ==========Login Section Section Starts Here========== -->
<div class="login-section padding-top padding-bottom">
  <div class="container">
    <div class="account-wrapper">
      <h3 class="title">Вход</h3>
      <div class="">
        <form method="post" action="" class="">
          {% csrf_token %}
           <div class="form-group">
            <label for="exampleInputEmail1" class="black-text">Логин</label>
            {{ form.username }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1"  class="black-text">Пароль</label>
            {{ form.password }}
          </div>
          <button type="submit" class="btn btn-primary">Войти</button>
        </form>
      </div>
      
      <div class="account-bottom">
        <span class="d-block cate pt-10"
          >Нету аккаунта?
          <a href="{% url 'tourism:register' %}">Зарегестрироваться</a></span
        >
      </div>
      <!-- ==========Login Section Section Ends Here========== -->
      {% endblock content %}
    </div>
  </div>
</div>

tour/templates/tour/order_room.html
{% extends 'base.html' %} {% block style %}
<link
  href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
  rel="stylesheet"
/>
{% endblock %} {% block title %}Order room
{% endblock title %} {% block content %}
<div class="intro">
  <h1>Заказ {{model_name}}</h1>
  <div class="container">
    <form method="post">
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock content %}

tour/templates/tour/order_tour.html
{% extends 'base.html' %} {% block style %}
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet" />
{% endblock %} {% block title %}Order transfer{% endblock title %} 
{% block content %}
<div class="intro">
    <h1>Заказ {{model_name}}</h1>
    <div class="container">
        <form method="post">
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock content %}

tour/templates/tour/order_transfer.html
{% extends 'base.html' %} {% block style %}
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet" />
{% endblock %} {% block title %}Order transfer{% endblock title %} 
{% block content %}
<div class="intro">
    <h1>Заказ {{model_name}}</h1>
    <div class="container">
        <form method="post">
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock content %}

tour/templates/tour/price_change.html
{% extends 'base.html' %} {% block style %}
<link
  href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
  rel="stylesheet"
/>
{% endblock %} {% block title %}Смена цены{% endblock title %} 
{% block content %}
<div class="intro">
  <h1>Смена цены</h1>
  <div class="container">
    {% if form %}
    <form method="post">
        {% if model %}
            <input type="hidden" name="model" value="{{model}}">
        {% endif %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock content %}

tour/templates/tour/register.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}
<!-- ==========Banner Section Starts Here========== -->
<section class="page-header bg_img" data-background="{% static 'images/banner/page-header.jpg' %}">
    <div class="container">
        <div class="page-header-content">
            <h1 class="title">Регистрация</h1>
            <ul class="breadcrumb">
                <li>
                    <a href='{% url "lessons_section:index" %}'>Главная</a>
                </li>
                <li>
                    Зарегистрируйтесь
                </li>
            </ul>
        </div>
    </div>
</section>
<!-- ==========Banner Section Ends Here========== -->


<!-- ==========Login Section Section Starts Here========== -->
<div class="login-section padding-top padding-bottom">
    <div class="container">
        <div class="account-wrapper">
            <h3 class="title">Зарегистрироваться</h3>
            <form method="POST" class="account-form" action='{% url "users_section:register" %}'>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.username }}
                </div>
                <div class="form-group">
                    {{ form.fio }}
                </div>
                <div class="form-group">
                    {{ form.password1 }}
                </div>
                <div class="form-group">
                    {{ form.password2 }}
                </div>
                <div class="form-group">
                    <span id='match' style="display:none">Пароли не совпадают</span>
                    <button id="subm_btn" type="submit" class="d-block custom-button"><span>Зарегистрироваться</span></button>
                </div>
            </form>
            <div class="account-bottom">
                <span class="d-block cate pt-10">Есть аккаунт? <a href="{% url 'users_section:login' %}">Login</a></span>
            </div>
        </div>
    </div>
</div>
<!-- ==========Login Section Section Ends Here========== -->
{% endblock main_content %}


{% block custom_scripts %}
<script>
    $('#password, #confirm_password').on('keyup', function () {
        if ($('#password').val() == $('#confirm_password').val()) {
            $('#subm_btn').removeAttr('disabled');
            $('#match').css('display', 'none');
        } else {
            $('#match').css('display', 'block');
            $('#match').css('color', 'red');
            $('#subm_btn').prop('disabled', true);
        }
    });
</script>
{% endblock custom_scripts %}

tour/templates/tour/registration.html
{% extends "base.html" %} {% load static %} {% block content %}

<!-- ==========Login Section Section Starts Here========== -->
<div class="login-section padding-top padding-bottom">
  <div class="container">
    <div class="account-wrapper">
      <h3 class="title">Зарегестрироваться</h3>

      <form
        method="POST"
        class="account-form"
        action='{% url "tourism:register" %}'
      >
        {% csrf_token %}
        {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Зарегестрироваться</button>
        </div>
      </form>
      <div class="account-bottom">
        <span class="d-block cate pt-10"
          >Есть аккаунт? <a href="{% url 'tourism:login' %}">Войти</a></span
        >
      </div>
    </div>
  </div>
</div>
<!-- ==========Login Section Section Ends Here========== -->
{% endblock content %}

tour/templates/tour/retrieve_users_orders.html
{% extends 'base.html' %} {% block style %}
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet" />
{% endblock %} {% block title %}Statistics{% endblock title %}
{% block content %}
<div class="intro"></div>
<div class="container">
    <h1>Заказы трансферов</h1>
    <table class="table table-light">
        <tbody>
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Пользователь</th>
                    <th scope="col">Название</th>
                    <th scope="col">Старт</th>
                    <th scope="col">Конец</th>
                    <th scope="col">Места</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Дата заказа</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Мэнеджер</th>
                </tr>
            </thead>
            {% for transfer_order in transferorders %}
            <tr>
                <td>{{ transfer_order.order_number }}</td>
                <td>{{ transfer_order.userid.username }}</td>
                <td>{{ transfer_order.transfer.title }}</td>
                <td>{{ transfer_order.startdate }}</td>
                <td>{{ transfer_order.enddate }}</td>
                <td>{{ transfer_order.places }}</td>
                <td>{{ transfer_order.time_differnce }}</td>
                <td>{{ transfer_order.orderdate }}</td>
                <td>{{ transfer_order.status }}</td>
                <td>{{ transfer_order.manager.user.username }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h1>Заказы туров</h1>
    <table class="table table-light">
        <tbody>
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Пользователь</th>
                    <th scope="col">Название</th>
                    <th scope="col">Старт</th>
                    <th scope="col">Конец</th>
                    <th scope="col">Места</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Дата заказа</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Мэнеджер</th>
                </tr>
            </thead>
            {% for tour_order in tourorders %}
            <tr>
                <td>{{ tour_order.order_number }}</td>
                <td>{{ tour_order.userid.username }}</td>
                <td>{{ tour_order.tour.title }}</td>
                <td>{{ tour_order.startdate }}</td>
                <td>{{ tour_order.enddate }}</td>
                <td>{{ tour_order.places }}</td>
                <td>{{ tour_order.time_differnce }}</td>
                <td>{{ tour_order.orderdate }}</td>
                <td>{{ tour_order.status }}</td>
                <td>{{ tour_order.manager.user.username }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h1>Заказы комнат</h1>
    <table style="margin-bottom: 100px;" class="table table-light">
        <tbody>
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Пользователь</th>
                    <th scope="col">Название</th>
                    <th scope="col">Старт</th>
                    <th scope="col">Конец</th>
                    <th scope="col">Места</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Дата заказа</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Мэнеджер</th>
                </tr>
            </thead>
            {% for room_order in roomorders %}
            <tr>
                <td>{{ room_order.order_number }}</td>
                <td>{{ room_order.userid.username }}</td>
                <td>{{ room_order.tour.title }}</td>
                <td>{{ room_order.startdate }}</td>
                <td>{{ room_order.enddate }}</td>
                <td>{{ room_order.places }}</td>
                <td>{{ room_order.time_differnce }}</td>
                <td>{{ room_order.orderdate }}</td>
                <td>{{ room_order.status }}</td>
                <td>{{ room_order.manager.user.username }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %}

tour/templates/tour/status_change.html
{% extends 'base.html' %} {% block style %}
<link
  href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
  rel="stylesheet"
/>
{% endblock %} {% block title %}Смена статуса заказа{% endblock title %} 
{% block content %}
<div class="intro">
  <h1>Смена статуса заказа</h1>
  <div class="container">
    {% if form %}
    <form method="post">
        {% if model %}
            <input type="hidden" name="model" value="{{model}}">
        {% endif %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock content %}